namespace lilToon.PCSS.Runtime
{
    // ... existing code ...
    // 例: [SerializeField] private float emissionStrength;
    // public float EmissionStrength { get => emissionStrength; set => emissionStrength = value; }
    // ... existing code ...
}
// ... existing code ... 